#!/bin/sh +xv
OUT_DIR=debug
BASE_URL=http://localhost:8000/debug
java -Djava.util.logging.config.file=logging.properties \
    -cp target/classes:target/dependency/* \
    saka1029.shinryo.main.Main \
    -o $OUT_DIR \
    -b $BASE_URL \
    $*
